In [83]:
import warnings
warnings.filterwarnings("ignore")

from tennisvenues_scraper import *

In [2]:
import os
import json

print("Imports básicos OK")

Imports básicos OK

In [3]:
import requests

print("requests OK")

requests OK

In [4]:
from bs4 import BeautifulSoup

print("BeautifulSoup OK")

BeautifulSoup OK

In [6]:
url = "https://example.com"

response = requests.get(url, verify=False)

print(response.status_code)

200

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'example.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [7]:
html = response.text

print(html[:500])

<!doctype html><html lang="en"><head><title>Example Domain</title><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{background:#eee;width:60vw;margin:15vh auto;font-family:system-ui,sans-serif}h1{font-size:1.5em}div{opacity:0.8}a:link,a:visited{color:#348}</style></head><body><div><h1>Example Domain</h1><p>This domain is for use in documentation examples without needing permission. Avoid use in operations.</p><p><a href="https://iana.org/domains/example">Learn more<

In [8]:
soup = BeautifulSoup(html, "html.parser")

print(soup.title)

<title>Example Domain</title>

In [9]:
url = "https://www.tennisvenues.com.au/booking/mowbray-public-school"

response = requests.get(url, verify=False)

print(response.status_code)

200

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [10]:
html = response.text

print(html[:2000])

<!DOCTYPE html>



<html lang="en">

<head>
	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
 	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="author" content="TennisVenues.com.au"/>
  	<meta name="copyright" content="TennisVenues.com.au"/>
  	<meta name="robots" content="index,follow">
  	<meta name="description" content="Tennis court booking in Mowbray Public School Tennis Courts">
  	<meta name="keywords" content="tennis court hire, tennis courts near me, tennis clubs, tennis centres, tennis courts, tennis venues, tennis clubs directory, book a court, court booking, tennis online booking, tennis community">


		<link rel="canonical" href="https://www.tennisvenues.com.au/booking/mowbray-public-school"/>


	<title>Book a Court | Mowbray Public School Tennis Courts in Lane Cove NSW</title>



 	<link href="/img/favicon.png" rel="shortcut icon">





	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

	<!-- font awesome CSS -->
	<link href="/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">



		<script  src="https://code.jquery.com/jquery-3.2.1.js"  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="  crossorigin="anonymous"></script>



	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt

In [11]:
keywords = ["court", "booking", "available", "slot", "time", "calendar", "ajax", "api"]

html_lower = html.lower()

for word in keywords:
    print(word, "->", word in html_lower)

court -> True
booking -> True
available -> True
slot -> False
time -> True
calendar -> True
ajax -> True
api -> True

In [12]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, "html.parser")
scripts = soup.find_all("script")

print("Cantidad de scripts:", len(scripts))

Cantidad de scripts: 13

In [13]:
for i, script in enumerate(scripts):
    content = script.get_text(" ", strip=True)
    src = script.get("src")
    
    if src:
        if any(x in src.lower() for x in ["api", "book", "court", "calendar", "ajax"]):
            print(f"\nSCRIPT SRC {i}:")
            print(src)
    else:
        if any(x in content.lower() for x in ["api", "book", "court", "calendar", "ajax", "availability"]):
            print(f"\nINLINE SCRIPT {i}:")
            print(content[:1000])
            print("-" * 80)

INLINE SCRIPT 5:
var mobile_view_enabled = false;
$(document).ready(function(){


	let booking_view_md = new MobileDetect(window.navigator.userAgent);
	if(booking_view_md.phone() != null || booking_view_md.tablet() != null)
	{
		mobile_view_enabled = true;
	}



	console.log("mobile view enabled:" + mobile_view_enabled)
})
--------------------------------------------------------------------------------

INLINE SCRIPT 6:
var desktop_script_enabled = true;

	$(function() {
		desktop_script_enabled = !mobile_view_enabled;

		if(!desktop_script_enabled) return;
		$('#datepicker').datepicker({
			minDate: new Date(2026, 3 - 1, 11)
			, maxDate: "+14D"
			, dateFormat: 'yymmdd'
			, defaultDate: "20260311"
			, onSelect: function(dateText, inst) {
				loadBookingData(0);
				$('#datepicker').blur();
			}
		});

	});

	function loadBookingData(offset, page) {
		if(!desktop_script_enabled) return;


		var currentDate = $('#datepicker').datepicker('getDate');
		if (currentDate==undefined) currentDate = new Date(); // Set to today if datepicker returns undefined date.
		// alert("currentDate="+currentDate);


		var newDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()+offset, 0, 0, 0);
		// alert("newDate="+newDate);

		// alert("setting picker to "+newDate.getDate()+"/"+(newDate.getMonth()+1)+"/"+newDate.getFullYear());



--------------------------------------------------------------------------------

INLINE SCRIPT 7:
$(document).ready(function() {
			if(!desktop_script_enabled) return;
			if ($('a#prev_day_button').length > 0)
			{
				$('a#prev_day_button').click(function(event){
					loadBookingData(-1);
			   	});
			}

			if ($('a#next_day_button').length > 0)
			{
				$('a#next_day_button').click(function(event){
					loadBookingData(1);
			   	});
			}

			//Ajax activity indicator bound to ajax start/stop document events
			if ($('#busy_img').length > 0)
			{
				$(document).ajaxStart(function(){
					$('#busy_img').show();
				}).ajaxStop(function(){
					$('#busy_img').hide();
				});
			}

			loadBookingData(0);
		 }); // End document ready function //
--------------------------------------------------------------------------------

INLINE SCRIPT 8:
var resourceChangedScrollDownEnabled = false;
var mobile_script_enabled = false;

$(function() {
	mobile_script_enabled = mobile_view_enabled;

	if(!mobile_script_enabled) return;

	setupDatePicker();

    setDatePickerDate(new Date('2026-03-11'));




	$("#available_resources" ).change(function() {

		resourceChangedScrollDownEnabled = true;
		scrollDownToResource();

	});

});



function reloadCalendarView(date)
{
	if(!mobile_script_enabled) return;
	console.log("mobile reloadCalendarView...date="+date);

	$("div#mobile-booking-data").hide();
	$.ajax({
		   url: "/booking/mowbray-public-school/fetch-booking-data",
		   cache: false,
		   data: {
			 	client_id: 'mowbray-public-school'
			 	, venue_id: '2398'
			 	, resource_id: ''
			 	, date: date
			 	, isMobileView : true
		   },
		   success: function(html){
			  /*  Upon successful return, render the div using returned html. */
		   		$("div#mobile-booking-data").htm
--------------------------------------------------------------------------------

INLINE SCRIPT 11:
{
  "@context": "http://www.schema.org",
  "@type": "TennisComplex",
  "name": "Mowbray Public School Tennis Courts",
  "url": "",

  "description": "Mowbray Public School Tennis Courts in Lane Cove NSW",
  "telephone": "0412 387 276",

  	"image": [


    		"https://d24lqeczfu7s1y.cloudfront.net/venue/mowbray-public-school/gpatennis_mowbray_public_school.jpg"

   ],


  	"geo": {
    	"@type": "GeoCoordinates",
    	"latitude": -33.804842,
    	"longitude": 151.1559289
  	},

	"hasMap": {
 		"@type": "Map",
   		"mapType": "VenueMap",
   		"url":  "https://www.google.com/maps/search/?api=1&query=-33.804842,151.1559289"
   	},

  "address": {
    "@type": "PostalAddress",
    "streetAddress": "Mowbray Rd and Hatfield St",
    "addressLocality": "Lane Cove",
    "addressRegion": "NSW",
    "postalCode": "2066",
    "addressCountry": "AU"
  }
}
--------------------------------------------------------------------------------

INLINE SCRIPT 12:
$(document).ready(function(){
	if(mobile_view_enabled)
	{
		$("#desktop_booking_view").html('');
		$("#mobile_booking_view").show();
	}
	else
	{
		$("#mobile_booking_view").html('');
		$("#desktop_booking_view").show();
	}

})
--------------------------------------------------------------------------------

In [14]:
print("TITLE:")
print(soup.title.get_text(strip=True))

print("\nPrimeros textos visibles:")
texts = soup.stripped_strings

for i, t in enumerate(texts):
    if i >= 50:
        break
    print(t)

TITLE:
Book a Court | Mowbray Public School Tennis Courts in Lane Cove NSW

Primeros textos visibles:
Book a Court | Mowbray Public School Tennis Courts in Lane Cove NSW
Mowbray Public School Tennis Courts
Mowbray Rd and Hatfield St,
Lane Cove, NSW 2066
View Booking Info
Court Hire Rate
×
COURT HIRE RATES
PEAK:
Mon-Fri 5 PM-10 PM
Sat/Sun All Day
$30 p/h
OFF PEAK:
Mon-Fri 7 AM-5 PM
$27 p/h
Please note:
Payments made by Credit Card will incur a small processing fee.
For permanent bookings please contact
Gian on 0412387276
Please note 48hrs notice is required for changes or cancellations.  A credit voucher will be issued for your next booking.
If courts are wet please do not play as they are slippery and dangerous. A credit voucher will be issued instead when notified.
Login
/
Register
Previous
Today
Next
Court 1
Court 2
Court 3
Switch to
Desktop View
Powered by
SportLogic
Mowbray Public School Tennis Courts
Login
/
Register
< Prev Day
Next Day >
Mowbray Rd and Hatfield St,
Lane Cove, NSW 2066
Available
Not Available
COURT HIRE RATES
PEAK:
Mon-Fri 5 PM-10 PM
Sat/Sun All Day
$30 p/h
OFF PEAK:

In [15]:
for i, script in enumerate(scripts):
    content = script.get_text(" ", strip=True)
    if "fetch-booking-data" in content:
        print(f"\nSCRIPT {i}")
        print(content[:3000])
        print("\n" + "="*100 + "\n")

SCRIPT 6
var desktop_script_enabled = true;

	$(function() {
		desktop_script_enabled = !mobile_view_enabled;

		if(!desktop_script_enabled) return;
		$('#datepicker').datepicker({
			minDate: new Date(2026, 3 - 1, 11)
			, maxDate: "+14D"
			, dateFormat: 'yymmdd'
			, defaultDate: "20260311"
			, onSelect: function(dateText, inst) {
				loadBookingData(0);
				$('#datepicker').blur();
			}
		});

	});

	function loadBookingData(offset, page) {
		if(!desktop_script_enabled) return;


		var currentDate = $('#datepicker').datepicker('getDate');
		if (currentDate==undefined) currentDate = new Date(); // Set to today if datepicker returns undefined date.
		// alert("currentDate="+currentDate);


		var newDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()+offset, 0, 0, 0);
		// alert("newDate="+newDate);

		// alert("setting picker to "+newDate.getDate()+"/"+(newDate.getMonth()+1)+"/"+newDate.getFullYear());


		$('#datepicker').datepicker('setDate', newDate);


		var newDate = $('#datepicker').datepicker('getDate');
		// alert("pickedDate="+pickedDate);


		var yearStr = "" + newDate.getFullYear();

		var month = newDate.getMonth()+1;
		var monthStr = "" + month;
		if (month < 10) monthStr = "0" + monthStr;

		var date = newDate.getDate();
		var dateStr = "" + date;
		if (date < 10) dateStr = "0" + dateStr;

		var yyyymmdd = yearStr + monthStr + dateStr;

		// Fetch booking data on the specified date.
		fetchBookingDate(yyyymmdd, page);

		var yearLabel = yearStr;
		var monthLabel = "";
		var dayLabel = "";

		if (month==1)
			monthLabel = "January";
		else if (month==2)
			monthLabel = "February";
		else if (month==3)
			monthLabel = "March";
		else if (month==4)
			monthLabel = "April";
		else if (month==5)
			monthLabel = "May";
		else if (month==6)
			monthLabel = "June";
		else if (month==7)
			monthLabel = "July";
		else if (month==8)
			monthLabel = "August";
		else if (month==9)
			monthLabel = "September";
		else if (month==10)
			monthLabel = "October";
		else if (month==11)
			monthLabel = "November";
		else if (month==12)
			monthLabel = "December";

		var day = newDate.getDay();

		if (day==0)
			dayLabel = "Sunday";
		else if (day==1)
			dayLabel = "Monday";
		else if (day==2)
			dayLabel = "Tuesday";
		else if (day==3)
			dayLabel = "Wednesday";
		else if (day==4)
			dayLabel = "Thursday";
		else if (day==5)
			dayLabel = "Friday";
		else if (day==6)
			dayLabel = "Saturday";

		$('#date-display').html(date+" "+monthLabel+" "+yearLabel+" ("+dayLabel+")");
	}

	function fetchBookingDate(yyyymmdd, page) {
		if(!desktop_script_enabled) return;
		console.log("desktop reloadCalendarView...date=" + yyyymmdd);

		$.ajax({
			   url: "/booking/mowbray-public-school/fetch-booking-data",
			   cache: false,
			   data: {
				 	client_id: 'mowbray-public-school'


====================================================================================================


SCRIPT 8
var resourceChangedScrollDownEnabled = false;
var mobile_script_enabled = false;

$(function() {
	mobile_script_enabled = mobile_view_enabled;

	if(!mobile_script_enabled) return;

	setupDatePicker();

    setDatePickerDate(new Date('2026-03-11'));




	$("#available_resources" ).change(function() {

		resourceChangedScrollDownEnabled = true;
		scrollDownToResource();

	});

});



function reloadCalendarView(date)
{
	if(!mobile_script_enabled) return;
	console.log("mobile reloadCalendarView...date="+date);

	$("div#mobile-booking-data").hide();
	$.ajax({
		   url: "/booking/mowbray-public-school/fetch-booking-data",
		   cache: false,
		   data: {
			 	client_id: 'mowbray-public-school'
			 	, venue_id: '2398'
			 	, resource_id: ''
			 	, date: date
			 	, isMobileView : true
		   },
		   success: function(html){
			  /*  Upon successful return, render the div using returned html. */
		   		$("div#mobile-booking-data").html(html);
		   		$("div#mobile-booking-data").show();


		   		if($("#C1_available_time a").length == 0)
		   			{
		   			$("#C1_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#C2_available_time a").length == 0)
		   			{
		   			$("#C2_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#C3_available_time a").length == 0)
		   			{
		   			$("#C3_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if(resourceChangedScrollDownEnabled)
		   			scrollDownToResource();

		   }
		 });

}

function setupDatePicker() {
	if(!mobile_script_enabled) return;
	var maxDate = new Date();
	maxDate.setDate(maxDate.getDate() + 14);
	$(".mobile-date-picker").flatpickr({
			altFormat: "j F, Y",
		    dateFormat: "d-M-Y l",
		    minDate: new Date(),
		    disableMobile: "true",
		    wrap:true,
		    maxDate: maxDate,
		    onChange: function(selectedDates, dateStr, instance) {
		    		datePickerDateChanged();
		    }
    	}
   	);
}

function getDatePicker() {
	if(!mobile_script_enabled) return;
	return document.querySelector(".mobile-date-picker")._flatpickr;
}


function getDatePickerDate()
{
	if(!mobile_script_enabled) return;
	const fp = getDatePicker();
	return fp.selectedDates[0];
}

function setDatePickerDate(date)
{
	if(!mobile_script_enabled) return;
	console.log('set datepicker to '+date);
	const fp = getDatePicker();
	// fp.jumpToDate(date);
	fp.setDate(date);


	if (getDatePickerDate()==null) fp.setDate(new Date());

	datePickerDateChanged();
}


	function datePickerDateChanged()
	{
		if(!mobile_script_enabled) return;
		var picked= getDatePickerDate();
		console.log('picked=' + picked);
		if (picked==null) return;
		reload

====================================================================================================

In [16]:
for i, script in enumerate(scripts):
    content = script.get_text(" ", strip=True)
    if "loadBookingData" in content:
        print(f"\nSCRIPT {i}")
        print(content[:5000])
        print("\n" + "="*100 + "\n")

SCRIPT 6
var desktop_script_enabled = true;

	$(function() {
		desktop_script_enabled = !mobile_view_enabled;

		if(!desktop_script_enabled) return;
		$('#datepicker').datepicker({
			minDate: new Date(2026, 3 - 1, 11)
			, maxDate: "+14D"
			, dateFormat: 'yymmdd'
			, defaultDate: "20260311"
			, onSelect: function(dateText, inst) {
				loadBookingData(0);
				$('#datepicker').blur();
			}
		});

	});

	function loadBookingData(offset, page) {
		if(!desktop_script_enabled) return;


		var currentDate = $('#datepicker').datepicker('getDate');
		if (currentDate==undefined) currentDate = new Date(); // Set to today if datepicker returns undefined date.
		// alert("currentDate="+currentDate);


		var newDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()+offset, 0, 0, 0);
		// alert("newDate="+newDate);

		// alert("setting picker to "+newDate.getDate()+"/"+(newDate.getMonth()+1)+"/"+newDate.getFullYear());


		$('#datepicker').datepicker('setDate', newDate);


		var newDate = $('#datepicker').datepicker('getDate');
		// alert("pickedDate="+pickedDate);


		var yearStr = "" + newDate.getFullYear();

		var month = newDate.getMonth()+1;
		var monthStr = "" + month;
		if (month < 10) monthStr = "0" + monthStr;

		var date = newDate.getDate();
		var dateStr = "" + date;
		if (date < 10) dateStr = "0" + dateStr;

		var yyyymmdd = yearStr + monthStr + dateStr;

		// Fetch booking data on the specified date.
		fetchBookingDate(yyyymmdd, page);

		var yearLabel = yearStr;
		var monthLabel = "";
		var dayLabel = "";

		if (month==1)
			monthLabel = "January";
		else if (month==2)
			monthLabel = "February";
		else if (month==3)
			monthLabel = "March";
		else if (month==4)
			monthLabel = "April";
		else if (month==5)
			monthLabel = "May";
		else if (month==6)
			monthLabel = "June";
		else if (month==7)
			monthLabel = "July";
		else if (month==8)
			monthLabel = "August";
		else if (month==9)
			monthLabel = "September";
		else if (month==10)
			monthLabel = "October";
		else if (month==11)
			monthLabel = "November";
		else if (month==12)
			monthLabel = "December";

		var day = newDate.getDay();

		if (day==0)
			dayLabel = "Sunday";
		else if (day==1)
			dayLabel = "Monday";
		else if (day==2)
			dayLabel = "Tuesday";
		else if (day==3)
			dayLabel = "Wednesday";
		else if (day==4)
			dayLabel = "Thursday";
		else if (day==5)
			dayLabel = "Friday";
		else if (day==6)
			dayLabel = "Saturday";

		$('#date-display').html(date+" "+monthLabel+" "+yearLabel+" ("+dayLabel+")");
	}

	function fetchBookingDate(yyyymmdd, page) {
		if(!desktop_script_enabled) return;
		console.log("desktop reloadCalendarView...date=" + yyyymmdd);

		$.ajax({
			   url: "/booking/mowbray-public-school/fetch-booking-data",
			   cache: false,
			   data: {
				 	client_id: 'mowbray-public-school'
				 	, venue_id: '2398'
				 	, resource_id: ''
				 	, date: yyyymmdd
				 	, page: page
			   },
			   success: function(html){

			   		$("div#booking_data").html(html);
			   		$("div#booking_data").show();
			   }
			 });
	}

====================================================================================================


SCRIPT 7
$(document).ready(function() {
			if(!desktop_script_enabled) return;
			if ($('a#prev_day_button').length > 0)
			{
				$('a#prev_day_button').click(function(event){
					loadBookingData(-1);
			   	});
			}

			if ($('a#next_day_button').length > 0)
			{
				$('a#next_day_button').click(function(event){
					loadBookingData(1);
			   	});
			}

			//Ajax activity indicator bound to ajax start/stop document events
			if ($('#busy_img').length > 0)
			{
				$(document).ajaxStart(function(){
					$('#busy_img').show();
				}).ajaxStop(function(){
					$('#busy_img').hide();
				});
			}

			loadBookingData(0);
		 }); // End document ready function //

====================================================================================================

In [17]:
import requests

url = "https://www.tennisvenues.com.au/booking/mowbray-public-school/fetch-booking-data"

payload = {
    "client_id": "mowbray-public-school",
    "venue_id": "2398",
    "resource_id": "",
    "date": "20260311",
    "page": 0
}

response = requests.get(url, params=payload, verify=False)

print(response.status_code)
print(response.text[:2000])

200
























<style>
table.BookingSheet {
	/* width: 90%; */
	/* width: 780px; */
	width: 100%;
	border-width: 0px 0px 0px 0px;
	border-spacing: 1px;
	border-style: outset outset outset outset;
	border-color: gray gray gray gray;
	border-collapse: collapse;
	background-color: white;
}

table.BookingSheet td {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}

table td.BookingSheetTimeLabel {
	width: 45px;
	font-family: Verdana,Arial,sans-serif;
	font-size: 15px;
	text-align: right;
	background-color: #E8E8E8;
	padding: 1px 10px 1px 3px;
	border-width: 0px 1px 0px 1px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	-moz-border-radius: 0px 0px 0px 0px;
}

table td.BookingSheetCategoryLabel {
	font-family: Verdana,Arial,sans-serif;
	font-size: 10pt;
	text-align: center;
	background-color: #E8E8E8;
	padding: 3px 1px 3px 1px;
	border-width: 1px 1px 1px 1px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	-moz-border-radius: 0px 0px 0px 0px;
}

table td.TimeCell {
	text-align: center;
	vertical-align: middle;
	height: 32px;
}

table td.NotAvailable {
	background-color: #D8D8D8;
	border-width: 1px 1px 1px 1px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	-moz-border-radius: 0px 0px 0px 0px;
}

table td.Available {
	background-color: white;
	border-width: 1px 1px 1px 1px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	-moz-border-radius: 0px 0px 0px 0px;
}

.NotAvailableColor {
	background-color: #D8D8D8;
}

.AvailableColor {
	background-color: white;
}

.GraySolidBorder {
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	border-width: 1px;
	-moz-border-radius: 0px

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [18]:
ajax_html = response.text

print("Largo del HTML AJAX:", len(ajax_html))

Largo del HTML AJAX: 11741

In [19]:
ajax_soup = BeautifulSoup(ajax_html, "html.parser")

print("HTML AJAX parseado")

HTML AJAX parseado

In [20]:
tables = ajax_soup.find_all("table")

print("Cantidad de tablas encontradas:", len(tables))

Cantidad de tablas encontradas: 2

In [21]:
booking_tables = ajax_soup.find_all("table", class_="BookingSheet")

print("BookingSheet tables encontradas:", len(booking_tables))

BookingSheet tables encontradas: 1

In [22]:
if booking_tables:
    booking_table = booking_tables[0]
    print(str(booking_table)[:3000])
else:
    print("No encontré tabla BookingSheet")

<table align="center" class="BookingSheet">
<thead>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;"> </td>
<td class="BookingSheetCategoryLabel">Court 1</td>
<td class="BookingSheetCategoryLabel">Court 2</td>
<td class="BookingSheetCategoryLabel">Court 3</td>
</tr>
</thead>
<tbody>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">6am</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-bottom: 0;"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">7am</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-bottom: 0;"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">8am</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-bottom: 0;"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">9am</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-bottom: 0;"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">10am</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-bottom: 0;"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">11am</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-bottom: 0;"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
</tr>
<tr>
<td class="BookingSheetTimeLabel" style="border-top: 1px solid gray;">12pm</td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </td>
<td class="TimeCell NotAvailable"> </

In [23]:
if booking_tables:
    texts = list(booking_table.stripped_strings)
    for t in texts[:100]:
        print(t)

Court 1
Court 2
Court 3
6am
7am
8am
9am
10am
11am
12pm
1pm
2pm
3pm
4pm
5pm
6pm
7pm
8pm
Wesley
Stuart
Wesley
Stuart
9pm
Wesley
Stuart
jason
Wesley
9:30pm
jason
10pm
11pm

In [24]:
rows = booking_table.find_all("tr")
print("Cantidad de filas:", len(rows))

Cantidad de filas: 37

In [25]:
for i, row in enumerate(rows[:8]):
    cells = row.find_all(["th", "td"])
    print(f"\nFILA {i} - cantidad de celdas: {len(cells)}")
    for j, cell in enumerate(cells):
        text = cell.get_text(" ", strip=True)
        classes = cell.get("class")
        print(f"  CELDA {j} | texto='{text}' | class={classes}")

FILA 0 - cantidad de celdas: 4
  CELDA 0 | texto='' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='Court 1' | class=['BookingSheetCategoryLabel']
  CELDA 2 | texto='Court 2' | class=['BookingSheetCategoryLabel']
  CELDA 3 | texto='Court 3' | class=['BookingSheetCategoryLabel']

FILA 1 - cantidad de celdas: 4
  CELDA 0 | texto='6am' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

FILA 2 - cantidad de celdas: 4
  CELDA 0 | texto='' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

FILA 3 - cantidad de celdas: 4
  CELDA 0 | texto='7am' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

FILA 4 - cantidad de celdas: 4
  CELDA 0 | texto='' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

FILA 5 - cantidad de celdas: 4
  CELDA 0 | texto='8am' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

FILA 6 - cantidad de celdas: 4
  CELDA 0 | texto='' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

FILA 7 - cantidad de celdas: 4
  CELDA 0 | texto='9am' | class=['BookingSheetTimeLabel']
  CELDA 1 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 2 | texto='' | class=['TimeCell', 'NotAvailable']
  CELDA 3 | texto='' | class=['TimeCell', 'NotAvailable']

In [26]:
unique_classes = set()

for row in rows:
    cells = row.find_all(["th", "td"])
    for cell in cells:
        classes = tuple(cell.get("class", []))
        unique_classes.add(classes)

for cls in sorted(unique_classes):
    print(cls)

('BookingSheetCategoryLabel',)
('BookingSheetTimeLabel',)
('TimeCell', 'Available')
('TimeCell', 'NotAvailable')

In [27]:
courts = []
data = []

# encabezados
header_cells = rows[0].find_all(["th", "td"])
for cell in header_cells[1:]:
    courts.append(cell.get_text(" ", strip=True))

print("Courts:", courts)

# filas de horarios
for row in rows[1:]:
    cells = row.find_all(["th", "td"])
    
    if len(cells) < 2:
        continue
    
    time_text = cells[0].get_text(" ", strip=True)
    
    for i, cell in enumerate(cells[1:]):
        court_name = courts[i] if i < len(courts) else f"Court_{i+1}"
        cell_text = cell.get_text(" ", strip=True)
        cell_classes = cell.get("class", [])
        
        if "NotAvailable" in cell_classes:
            status = "not_available"
        elif "Available" in cell_classes:
            status = "available"
        else:
            status = "unknown"
        
        data.append({
            "time": time_text,
            "court": court_name,
            "status": status,
            "text": cell_text,
            "classes": ", ".join(cell_classes)
        })

print("Filas creadas:", len(data))
data[:15]

Courts: ['Court 1', 'Court 2', 'Court 3']
Filas creadas: 108

[{'time': '6am',
  'court': 'Court 1',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '6am',
  'court': 'Court 2',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '6am',
  'court': 'Court 3',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '',
  'court': 'Court 1',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '',
  'court': 'Court 2',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '',
  'court': 'Court 3',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '7am',
  'court': 'Court 1',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '7am',
  'court': 'Court 2',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '7am',
  'court': 'Court 3',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '',
  'court': 'Court 1',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '',
  'court': 'Court 2',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '',
  'court': 'Court 3',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '8am',
  'court': 'Court 1',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '8am',
  'court': 'Court 2',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'},
 {'time': '8am',
  'court': 'Court 3',
  'status': 'not_available',
  'text': '',
  'classes': 'TimeCell, NotAvailable'}]

In [28]:
import pandas as pd

df = pd.DataFrame(data)
df.head(20)

   time    court         status text                 classes
0   6am  Court 1  not_available       TimeCell, NotAvailable
1   6am  Court 2  not_available       TimeCell, NotAvailable
2   6am  Court 3  not_available       TimeCell, NotAvailable
3        Court 1  not_available       TimeCell, NotAvailable
4        Court 2  not_available       TimeCell, NotAvailable
5        Court 3  not_available       TimeCell, NotAvailable
6   7am  Court 1  not_available       TimeCell, NotAvailable
7   7am  Court 2  not_available       TimeCell, NotAvailable
8   7am  Court 3  not_available       TimeCell, NotAvailable
9        Court 1  not_available       TimeCell, NotAvailable
10       Court 2  not_available       TimeCell, NotAvailable
11       Court 3  not_available       TimeCell, NotAvailable
12  8am  Court 1  not_available       TimeCell, NotAvailable
13  8am  Court 2  not_available       TimeCell, NotAvailable
14  8am  Court 3  not_available       TimeCell, NotAvailable
15       Court 1  not_available       TimeCell, NotAvailable
16       Court 2  not_available       TimeCell, NotAvailable
17       Court 3  not_available       TimeCell, NotAvailable
18  9am  Court 1  not_available       TimeCell, NotAvailable
19  9am  Court 2  not_available       TimeCell, NotAvailable

In [29]:
night_times = ["5pm", "6pm", "7pm", "8pm", "9pm", "10pm"]

df_night = df[df["time"].isin(night_times)]
df_night

    time    court         status    text                 classes
66   5pm  Court 1  not_available          TimeCell, NotAvailable
67   5pm  Court 2  not_available          TimeCell, NotAvailable
68   5pm  Court 3  not_available          TimeCell, NotAvailable
72   6pm  Court 1  not_available          TimeCell, NotAvailable
73   6pm  Court 2  not_available          TimeCell, NotAvailable
74   6pm  Court 3  not_available          TimeCell, NotAvailable
78   7pm  Court 1  not_available          TimeCell, NotAvailable
79   7pm  Court 2  not_available          TimeCell, NotAvailable
80   7pm  Court 3  not_available          TimeCell, NotAvailable
84   8pm  Court 1  not_available  Wesley  TimeCell, NotAvailable
85   8pm  Court 2  not_available  Stuart  TimeCell, NotAvailable
86   8pm  Court 3  not_available          TimeCell, NotAvailable
90   9pm  Court 1  not_available  Wesley  TimeCell, NotAvailable
91   9pm  Court 2  not_available  Stuart  TimeCell, NotAvailable
92   9pm  Court 3  not_available   jason  TimeCell, NotAvailable
96  10pm  Court 1  not_available          TimeCell, NotAvailable
97  10pm  Court 2  not_available          TimeCell, NotAvailable
98  10pm  Court 3  not_available          TimeCell, NotAvailable

In [31]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

def get_booking_dataframe(client_id, venue_id, date_yyyymmdd, page=0):
    url = f"https://www.tennisvenues.com.au/booking/{client_id}/fetch-booking-data"
    
    payload = {
        "client_id": client_id,
        "venue_id": venue_id,
        "resource_id": "",
        "date": date_yyyymmdd,
        "page": page
    }
    
    response = requests.get(url, params=payload, verify=False)
    
    if response.status_code != 200:
        raise Exception(f"Error HTTP: {response.status_code}")
    
    ajax_html = response.text
    ajax_soup = BeautifulSoup(ajax_html, "html.parser")
    
    booking_tables = ajax_soup.find_all("table", class_="BookingSheet")
    if not booking_tables:
        raise Exception("No encontré la tabla BookingSheet")
    
    booking_table = booking_tables[0]
    rows = booking_table.find_all("tr")
    
    courts = []
    data = []
    
    # encabezados
    header_cells = rows[0].find_all(["th", "td"])
    for cell in header_cells[1:]:
        courts.append(cell.get_text(" ", strip=True))
    
    # filas
    for row in rows[1:]:
        cells = row.find_all(["th", "td"])
        
        if len(cells) < 2:
            continue
        
        time_text = cells[0].get_text(" ", strip=True)
        
        for i, cell in enumerate(cells[1:]):
            court_name = courts[i] if i < len(courts) else f"Court_{i+1}"
            cell_text = cell.get_text(" ", strip=True)
            cell_classes = cell.get("class", [])
            
            if "NotAvailable" in cell_classes:
                status = "not_available"
            elif "Available" in cell_classes:
                status = "available"
            else:
                status = "unknown"
            
            data.append({
                "time": time_text,
                "court": court_name,
                "status": status,
                "text": cell_text,
                "classes": ", ".join(cell_classes)
            })
    
    return pd.DataFrame(data)

In [32]:
df_mowbray = get_booking_dataframe(
    client_id="mowbray-public-school",
    venue_id="2398",
    date_yyyymmdd="20260311"
)

df_mowbray.head(20)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

   time    court         status text                 classes
0   6am  Court 1  not_available       TimeCell, NotAvailable
1   6am  Court 2  not_available       TimeCell, NotAvailable
2   6am  Court 3  not_available       TimeCell, NotAvailable
3        Court 1  not_available       TimeCell, NotAvailable
4        Court 2  not_available       TimeCell, NotAvailable
5        Court 3  not_available       TimeCell, NotAvailable
6   7am  Court 1  not_available       TimeCell, NotAvailable
7   7am  Court 2  not_available       TimeCell, NotAvailable
8   7am  Court 3  not_available       TimeCell, NotAvailable
9        Court 1  not_available       TimeCell, NotAvailable
10       Court 2  not_available       TimeCell, NotAvailable
11       Court 3  not_available       TimeCell, NotAvailable
12  8am  Court 1  not_available       TimeCell, NotAvailable
13  8am  Court 2  not_available       TimeCell, NotAvailable
14  8am  Court 3  not_available       TimeCell, NotAvailable
15       Court 1  not_available       TimeCell, NotAvailable
16       Court 2  not_available       TimeCell, NotAvailable
17       Court 3  not_available       TimeCell, NotAvailable
18  9am  Court 1  not_available       TimeCell, NotAvailable
19  9am  Court 2  not_available       TimeCell, NotAvailable

In [33]:
night_times = ["5pm", "6pm", "7pm", "8pm", "9pm", "10pm"]

df_mowbray_night = df_mowbray[df_mowbray["time"].isin(night_times)]
df_mowbray_night

    time    court         status    text                 classes
66   5pm  Court 1  not_available          TimeCell, NotAvailable
67   5pm  Court 2  not_available          TimeCell, NotAvailable
68   5pm  Court 3  not_available          TimeCell, NotAvailable
72   6pm  Court 1  not_available          TimeCell, NotAvailable
73   6pm  Court 2  not_available          TimeCell, NotAvailable
74   6pm  Court 3  not_available          TimeCell, NotAvailable
78   7pm  Court 1  not_available          TimeCell, NotAvailable
79   7pm  Court 2  not_available          TimeCell, NotAvailable
80   7pm  Court 3  not_available          TimeCell, NotAvailable
84   8pm  Court 1  not_available  Wesley  TimeCell, NotAvailable
85   8pm  Court 2  not_available  Stuart  TimeCell, NotAvailable
86   8pm  Court 3  not_available          TimeCell, NotAvailable
90   9pm  Court 1  not_available  Wesley  TimeCell, NotAvailable
91   9pm  Court 2  not_available  Stuart  TimeCell, NotAvailable
92   9pm  Court 3  not_available   jason  TimeCell, NotAvailable
96  10pm  Court 1  not_available          TimeCell, NotAvailable
97  10pm  Court 2  not_available          TimeCell, NotAvailable
98  10pm  Court 3  not_available          TimeCell, NotAvailable

In [34]:
available_mowbray = df_mowbray_night[df_mowbray_night["status"] == "available"]
available_mowbray

Empty DataFrame
Columns: [time, court, status, text, classes]
Index: []

In [35]:
selected_time = "7pm"

df_mowbray_7pm = df_mowbray[df_mowbray["time"] == selected_time]
df_mowbray_7pm

   time    court         status text                 classes
78  7pm  Court 1  not_available       TimeCell, NotAvailable
79  7pm  Court 2  not_available       TimeCell, NotAvailable
80  7pm  Court 3  not_available       TimeCell, NotAvailable

In [36]:
available_at_7pm = df_mowbray_7pm[df_mowbray_7pm["status"] == "available"]
available_at_7pm

Empty DataFrame
Columns: [time, court, status, text, classes]
Index: []

In [37]:
def get_available_courts_for_time(client_id, venue_id, date_yyyymmdd, selected_time, page=0):
    df = get_booking_dataframe(
        client_id=client_id,
        venue_id=venue_id,
        date_yyyymmdd=date_yyyymmdd,
        page=page
    )
    
    df_time = df[df["time"] == selected_time].copy()
    df_available = df_time[df_time["status"] == "available"].copy()
    
    return df_available

In [38]:
available_mowbray_7pm = get_available_courts_for_time(
    client_id="mowbray-public-school",
    venue_id="2398",
    date_yyyymmdd="20260311",
    selected_time="7pm"
)

available_mowbray_7pm

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Empty DataFrame
Columns: [time, court, status, text, classes]
Index: []

In [39]:
def get_available_court_names(client_id, venue_id, date_yyyymmdd, selected_time, page=0):
    df_available = get_available_courts_for_time(
        client_id=client_id,
        venue_id=venue_id,
        date_yyyymmdd=date_yyyymmdd,
        selected_time=selected_time,
        page=page
    )
    
    return df_available["court"].tolist()

In [40]:
court_names = get_available_court_names(
    client_id="mowbray-public-school",
    venue_id="2398",
    date_yyyymmdd="20260311",
    selected_time="7pm"
)

print(court_names)

[]

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [41]:
url = "https://www.tennisvenues.com.au/booking/artarmon-tennis"

response = requests.get(url, verify=False)
html = response.text
soup = BeautifulSoup(html, "html.parser")
scripts = soup.find_all("script")

for i, script in enumerate(scripts):
    content = script.get_text(" ", strip=True)
    if "fetch-booking-data" in content or "venue_id" in content:
        print(f"\nSCRIPT {i}")
        print(content[:8000])
        print("\n" + "="*100 + "\n")

SCRIPT 6
var desktop_script_enabled = true;

	$(function() {
		desktop_script_enabled = !mobile_view_enabled;

		if(!desktop_script_enabled) return;
		$('#datepicker').datepicker({
			minDate: new Date(2026, 3 - 1, 11)
			, maxDate: "+30D"
			, dateFormat: 'yymmdd'
			, defaultDate: "20260311"
			, onSelect: function(dateText, inst) {
				loadBookingData(0);
				$('#datepicker').blur();
			}
		});

	});

	function loadBookingData(offset, page) {
		if(!desktop_script_enabled) return;


		var currentDate = $('#datepicker').datepicker('getDate');
		if (currentDate==undefined) currentDate = new Date(); // Set to today if datepicker returns undefined date.
		// alert("currentDate="+currentDate);


		var newDate = new Date(currentDate.getFullYear(), currentDate.getMonth(), currentDate.getDate()+offset, 0, 0, 0);
		// alert("newDate="+newDate);

		// alert("setting picker to "+newDate.getDate()+"/"+(newDate.getMonth()+1)+"/"+newDate.getFullYear());


		$('#datepicker').datepicker('setDate', newDate);


		var newDate = $('#datepicker').datepicker('getDate');
		// alert("pickedDate="+pickedDate);


		var yearStr = "" + newDate.getFullYear();

		var month = newDate.getMonth()+1;
		var monthStr = "" + month;
		if (month < 10) monthStr = "0" + monthStr;

		var date = newDate.getDate();
		var dateStr = "" + date;
		if (date < 10) dateStr = "0" + dateStr;

		var yyyymmdd = yearStr + monthStr + dateStr;

		// Fetch booking data on the specified date.
		fetchBookingDate(yyyymmdd, page);

		var yearLabel = yearStr;
		var monthLabel = "";
		var dayLabel = "";

		if (month==1)
			monthLabel = "January";
		else if (month==2)
			monthLabel = "February";
		else if (month==3)
			monthLabel = "March";
		else if (month==4)
			monthLabel = "April";
		else if (month==5)
			monthLabel = "May";
		else if (month==6)
			monthLabel = "June";
		else if (month==7)
			monthLabel = "July";
		else if (month==8)
			monthLabel = "August";
		else if (month==9)
			monthLabel = "September";
		else if (month==10)
			monthLabel = "October";
		else if (month==11)
			monthLabel = "November";
		else if (month==12)
			monthLabel = "December";

		var day = newDate.getDay();

		if (day==0)
			dayLabel = "Sunday";
		else if (day==1)
			dayLabel = "Monday";
		else if (day==2)
			dayLabel = "Tuesday";
		else if (day==3)
			dayLabel = "Wednesday";
		else if (day==4)
			dayLabel = "Thursday";
		else if (day==5)
			dayLabel = "Friday";
		else if (day==6)
			dayLabel = "Saturday";

		$('#date-display').html(date+" "+monthLabel+" "+yearLabel+" ("+dayLabel+")");
	}

	function fetchBookingDate(yyyymmdd, page) {
		if(!desktop_script_enabled) return;
		console.log("desktop reloadCalendarView...date=" + yyyymmdd);

		$.ajax({
			   url: "/booking/artarmon-tennis/fetch-booking-data",
			   cache: false,
			   data: {
				 	client_id: 'artarmon-tennis'
				 	, venue_id: '3472'
				 	, resource_id: ''
				 	, date: yyyymmdd
				 	, page: page
			   },
			   success: function(html){

			   		$("div#booking_data").html(html);
			   		$("div#booking_data").show();
			   }
			 });
	}

====================================================================================================


SCRIPT 8
var resourceChangedScrollDownEnabled = false;
var mobile_script_enabled = false;

$(function() {
	mobile_script_enabled = mobile_view_enabled;

	if(!mobile_script_enabled) return;

	setupDatePicker();

    setDatePickerDate(new Date('2026-03-11'));




	$("#available_resources" ).change(function() {

		resourceChangedScrollDownEnabled = true;
		scrollDownToResource();

	});

});



function reloadCalendarView(date)
{
	if(!mobile_script_enabled) return;
	console.log("mobile reloadCalendarView...date="+date);

	$("div#mobile-booking-data").hide();
	$.ajax({
		   url: "/booking/artarmon-tennis/fetch-booking-data",
		   cache: false,
		   data: {
			 	client_id: 'artarmon-tennis'
			 	, venue_id: '3472'
			 	, resource_id: ''
			 	, date: date
			 	, isMobileView : true
		   },
		   success: function(html){
			  /*  Upon successful return, render the div using returned html. */
		   		$("div#mobile-booking-data").html(html);
		   		$("div#mobile-booking-data").show();


		   		if($("#2c90815a7bbcd518017bd7e5adc60043_available_time a").length == 0)
		   			{
		   			$("#2c90815a7bbcd518017bd7e5adc60043_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#2c90815a7bbcd518017bd7e6cff20044_available_time a").length == 0)
		   			{
		   			$("#2c90815a7bbcd518017bd7e6cff20044_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#2c90815a7bbcd518017bd7e6cff20045_available_time a").length == 0)
		   			{
		   			$("#2c90815a7bbcd518017bd7e6cff20045_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#2c90815a7bbcd518017bd7e6cff20046_available_time a").length == 0)
		   			{
		   			$("#2c90815a7bbcd518017bd7e6cff20046_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#2c90815a7bbcd518017bd7e6cff20047_available_time a").length == 0)
		   			{
		   			$("#2c90815a7bbcd518017bd7e6cff20047_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if($("#2c90815a7bbcd518017bd7e6cff20048_available_time a").length == 0)
		   			{
		   			$("#2c90815a7bbcd518017bd7e6cff20048_available_time").append("<p style='margin-bottom: 0px;'>Not available.");



		   			}

		   		if(resourceChangedScrollDownEnabled)
		   			scrollDownToResource();

		   }
		 });

}

function setupDatePicker() {
	if(!mobile_script_enabled) return;
	var maxDate = new Date();
	maxDate.setDate(maxDate.getDate() + 30);
	$(".mobile-date-picker").flatpickr({
			altFormat: "j F, Y",
		    dateFormat: "d-M-Y l",
		    minDate: new Date(),
		    disableMobile: "true",
		    wrap:true,
		    maxDate: maxDate,
		    onChange: function(selectedDates, dateStr, instance) {
		    		datePickerDateChanged();
		    }
    	}
   	);
}

function getDatePicker() {
	if(!mobile_script_enabled) return;
	return document.querySelector(".mobile-date-picker")._flatpickr;
}


function getDatePickerDate()
{
	if(!mobile_script_enabled) return;
	const fp = getDatePicker();
	return fp.selectedDates[0];
}

function setDatePickerDate(date)
{
	if(!mobile_script_enabled) return;
	console.log('set datepicker to '+date);
	const fp = getDatePicker();
	// fp.jumpToDate(date);
	fp.setDate(date);


	if (getDatePickerDate()==null) fp.setDate(new Date());

	datePickerDateChanged();
}


	function datePickerDateChanged()
	{
		if(!mobile_script_enabled) return;
		var picked= getDatePickerDate();
		console.log('picked=' + picked);
		if (picked==null) return;
		reloadCalendarView(getFormattedDateStr(picked));
	}

	function adjustDatePickerDate(offset)
	{
	    var date = getDatePickerDate();
	    if (date==null) return;
		date.setDate(date.getDate()+offset);
		setDatePickerDate(date);
	}

	function adjustDatePickerDateToToday()
	{
		if(!mobile_script_enabled) return;
		setDatePickerDate(new Date());
	}

	function getFormattedDateStr(date) {
		if(!mobile_script_enabled) return;
		if (date==null) return null;
	var yearStr = "" + date.getFullYear();

	var month = date.getMonth()+1;
	var monthStr = "" + month;
	if (month < 10) monthStr = "0" + monthStr;

	var d = date.getDate();
	var dateStr = "" + d;
	if (d < 10) dateStr = "0" + dateStr;

	var yyyymmdd = yearStr + monthStr + dateStr;

	return yyyymmdd;
	}

	function scrollDownToResource(){
		if(!mobile_script_enabled) return;
		let selectIndex = $("select#available_resources").prop('selectedIndex');

		let selectedResource = '#'+$("select#available_resources").val() + "_info";
		let topPosition = $(selectedResource).offset().top;
		let targetPosition = topPosition - 150;
		 $('html,body').animate({
		        scrollTop: targetPosition
		    }, 'slow');
	}

====================================================================================================

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [44]:
from tennisvenues_scraper import (
    get_booking_dataframe,
    get_available_courts_for_time,
    get_available_court_names
)

In [45]:
get_available_court_names(
    client_id="mowbray-public-school",
    venue_id="2398",
    date_yyyymmdd="20260311",
    selected_time="7pm"
)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[]

In [46]:
get_available_court_names(
    client_id="artarmon-tennis",
    venue_id="3472",
    date_yyyymmdd="20260311",
    selected_time="7pm"
)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[]

In [47]:
df_artarmon = get_booking_dataframe(
    client_id="artarmon-tennis",
    venue_id="3472",
    date_yyyymmdd="20260311"
)

df_artarmon.head(20)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

   time    court         status text                 classes
0   6am  Court 1  not_available       TimeCell, NotAvailable
1   6am  Court 2  not_available       TimeCell, NotAvailable
2   6am  Court 3  not_available       TimeCell, NotAvailable
3   6am  Court 4  not_available       TimeCell, NotAvailable
4   6am  Court 5  not_available       TimeCell, NotAvailable
5   6am  Court 6  not_available       TimeCell, NotAvailable
6   7am  Court 1  not_available       TimeCell, NotAvailable
7   7am  Court 2  not_available       TimeCell, NotAvailable
8   7am  Court 3  not_available       TimeCell, NotAvailable
9   7am  Court 4  not_available       TimeCell, NotAvailable
10  7am  Court 5  not_available       TimeCell, NotAvailable
11  7am  Court 6  not_available       TimeCell, NotAvailable
12  8am  Court 1  not_available       TimeCell, NotAvailable
13  8am  Court 2  not_available       TimeCell, NotAvailable
14  8am  Court 3  not_available       TimeCell, NotAvailable
15  8am  Court 4  not_available       TimeCell, NotAvailable
16  8am  Court 5  not_available       TimeCell, NotAvailable
17  8am  Court 6  not_available       TimeCell, NotAvailable
18  9am  Court 1  not_available       TimeCell, NotAvailable
19  9am  Court 2  not_available       TimeCell, NotAvailable

In [48]:
night_times = ["5pm", "6pm", "7pm", "8pm", "9pm", "10pm"]

df_artarmon_night = df_artarmon[df_artarmon["time"].isin(night_times)]
df_artarmon_night

     time    court         status text                 classes
66    5pm  Court 1  not_available       TimeCell, NotAvailable
67    5pm  Court 2  not_available       TimeCell, NotAvailable
68    5pm  Court 3  not_available       TimeCell, NotAvailable
69    5pm  Court 4  not_available       TimeCell, NotAvailable
70    5pm  Court 5  not_available       TimeCell, NotAvailable
71    5pm  Court 6  not_available       TimeCell, NotAvailable
72    6pm  Court 1  not_available       TimeCell, NotAvailable
73    6pm  Court 2  not_available       TimeCell, NotAvailable
74    6pm  Court 3  not_available       TimeCell, NotAvailable
75    6pm  Court 4  not_available       TimeCell, NotAvailable
76    6pm  Court 5  not_available       TimeCell, NotAvailable
77    6pm  Court 6  not_available       TimeCell, NotAvailable
78    7pm  Court 1  not_available       TimeCell, NotAvailable
79    7pm  Court 2  not_available       TimeCell, NotAvailable
80    7pm  Court 3  not_available       TimeCell, NotAvailable
81    7pm  Court 4  not_available       TimeCell, NotAvailable
82    7pm  Court 5  not_available       TimeCell, NotAvailable
83    7pm  Court 6  not_available       TimeCell, NotAvailable
84    8pm  Court 1  not_available       TimeCell, NotAvailable
85    8pm  Court 2  not_available       TimeCell, NotAvailable
86    8pm  Court 3  not_available       TimeCell, NotAvailable
87    8pm  Court 4  not_available       TimeCell, NotAvailable
88    8pm  Court 5  not_available       TimeCell, NotAvailable
89    8pm  Court 6  not_available       TimeCell, NotAvailable
90    9pm  Court 1  not_available       TimeCell, NotAvailable
91    9pm  Court 2  not_available       TimeCell, NotAvailable
92    9pm  Court 3  not_available       TimeCell, NotAvailable
93    9pm  Court 4  not_available       TimeCell, NotAvailable
94    9pm  Court 5  not_available       TimeCell, NotAvailable
95    9pm  Court 6  not_available       TimeCell, NotAvailable
96   10pm  Court 1  not_available       TimeCell, NotAvailable
97   10pm  Court 2  not_available       TimeCell, NotAvailable
98   10pm  Court 3  not_available       TimeCell, NotAvailable
99   10pm  Court 4  not_available       TimeCell, NotAvailable
100  10pm  Court 5  not_available       TimeCell, NotAvailable
101  10pm  Court 6  not_available       TimeCell, NotAvailable

In [59]:
import importlib
import tennisvenues_scraper

importlib.reload(tennisvenues_scraper)

In [60]:
from tennisvenues_scraper import extract_venue_info_from_booking_page

In [61]:
extract_venue_info_from_booking_page(
    "https://www.tennisvenues.com.au/booking/ryde-tennis-centre"
)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

{'booking_url': 'https://www.tennisvenues.com.au/booking/ryde-tennis-centre',
 'client_id': 'ryde-tennis-centre',
 'venue_id': '2494'}

In [67]:
import importlib
import tennisvenues_scraper

importlib.reload(tennisvenues_scraper)

In [68]:
from tennisvenues_scraper import get_available_courts_from_url

In [69]:
get_available_courts_from_url(
    booking_url="https://www.tennisvenues.com.au/booking/ryde-tennis-centre",
    date_yyyymmdd="20260311",
    selected_time="7pm"
)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[]

In [76]:
venues = {
    "Mowbray": "https://www.tennisvenues.com.au/booking/mowbray-public-school",
    "Sydney Boys": "https://www.tennisvenues.com.au/booking/sydney-boys-high-school",
    "Artarmon": "https://www.tennisvenues.com.au/booking/artarmon-tennis",
    "Ryde": "https://www.tennisvenues.com.au/booking/ryde-tennis-centre",
    "Gosford": "https://www.tennisvenues.com.au/booking/gosford-tennis-club",
    "Snape Park": "https://www.tennisvenues.com.au/booking/snape-park-tc"
}

In [77]:
def check_all_venues(date, time):
    
    results = {}

    for name, url in venues.items():
        try:
            courts = get_available_courts_from_url(
                booking_url=url,
                date_yyyymmdd=date,
                selected_time=time
            )

            results[name] = courts

        except Exception as e:
            results[name] = f"error: {e}"

    return results

In [78]:
check_all_venues(
    date="20260311",
    time="7pm"
)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

{'Mowbray': [],
 'Sydney Boys': [],
 'Artarmon': [],
 'Ryde': [],
 'Gosford': [],
 'Snape Park': []}

In [73]:
check_all_venues(
    date="20260311",
    time="6pm"
)

C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\crist\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tennisvenues.com.au'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

{'Mowbray': [],
 'Sydney Boys': [],
 'Artarmon': [],
 'Ryde': [],
 'Gosford': [],
 'Snape Park': []}

In [81]:
check_all_venues(
    date="20260311",
    time="8pm"
)

{'Mowbray': [],
 'Sydney Boys': [],
 'Artarmon': [],
 'Ryde': [],
 'Gosford': ['Court 3 (Synthetic)',
  'Court 4 (Synthetic)',
  'Court 5 (Synthetic)',
  'Court 6 (Synthetic)',
  'Court 7 (Synthetic)',
  'Court 12 (Synthetic)',
  'Court 13 (Synthetic)'],
 'Snape Park': []}

In [84]:
def filter_only_available(results):

    available = {}

    for venue, courts in results.items():

        # si courts es una lista y tiene elementos
        if isinstance(courts, list) and len(courts) > 0:
            available[venue] = courts

    return available

In [85]:
results = check_all_venues(
    date="20260311",
    time="8pm"
)

available = filter_only_available(results)

available

{'Gosford': ['Court 3 (Synthetic)',
  'Court 4 (Synthetic)',
  'Court 5 (Synthetic)',
  'Court 6 (Synthetic)',
  'Court 7 (Synthetic)',
  'Court 12 (Synthetic)',
  'Court 13 (Synthetic)']}

In [86]:
def format_results_for_frontend(results):

    formatted = []

    for venue, courts in results.items():

        formatted.append({
            "venue": venue,
            "available_courts": len(courts),
            "courts": courts
        })

    return formatted

In [87]:
results = check_all_venues(
    date="20260311",
    time="8pm"
)

available = filter_only_available(results)

frontend_data = format_results_for_frontend(available)

frontend_data

[{'venue': 'Gosford',
  'available_courts': 7,
  'courts': ['Court 3 (Synthetic)',
   'Court 4 (Synthetic)',
   'Court 5 (Synthetic)',
   'Court 6 (Synthetic)',
   'Court 7 (Synthetic)',
   'Court 12 (Synthetic)',
   'Court 13 (Synthetic)']}]

In [88]:
VENUE_INFO = {
    "Mowbray": {
        "name": "Mowbray Public School Tennis Courts",
        "surface": "Hard Court",
        "location": "Lane Cove",
        "url": "https://www.tennisvenues.com.au/booking/mowbray-public-school"
    },
    "Sydney Boys": {
        "name": "Sydney Boys High School Tennis Courts",
        "surface": "Hard Court",
        "location": "Moore Park",
        "url": "https://www.tennisvenues.com.au/booking/sydney-boys-high-school"
    },
    "Artarmon": {
        "name": "Artarmon Tennis Centre",
        "surface": "Synthetic Grass",
        "location": "Artarmon",
        "url": "https://www.tennisvenues.com.au/booking/artarmon-tennis"
    },
    "Ryde": {
        "name": "Ryde Tennis Centre",
        "surface": "Synthetic Grass",
        "location": "Ryde",
        "url": "https://www.tennisvenues.com.au/booking/ryde-tennis-centre"
    },
    "Gosford": {
        "name": "Gosford Tennis Club",
        "surface": "Synthetic",
        "location": "Gosford",
        "url": "https://www.tennisvenues.com.au/booking/gosford-tennis-club"
    },
    "Snape Park": {
        "name": "Snape Park Tennis Centre",
        "surface": "Hard Court / Synthetic",
        "location": "Maroubra",
        "url": "https://www.tennisvenues.com.au/booking/snape-park-tc"
    }
}

In [89]:
def build_frontend_cards(results):

    cards = []

    for item in results:

        venue_key = item["venue"]
        info = VENUE_INFO.get(venue_key, {})

        card = {
            "name": info.get("name"),
            "location": info.get("location"),
            "surface": info.get("surface"),
            "url": info.get("url"),
            "available_courts": item["available_courts"],
            "courts": item["courts"]
        }

        cards.append(card)

    return cards

In [90]:
results = check_all_venues(
    date="20260311",
    time="8pm"
)

available = filter_only_available(results)

formatted = format_results_for_frontend(available)

cards = build_frontend_cards(formatted)

cards

[{'name': 'Gosford Tennis Club',
  'location': 'Gosford',
  'surface': 'Synthetic',
  'url': 'https://www.tennisvenues.com.au/booking/gosford-tennis-club',
  'available_courts': 7,
  'courts': ['Court 3 (Synthetic)',
   'Court 4 (Synthetic)',
   'Court 5 (Synthetic)',
   'Court 6 (Synthetic)',
   'Court 7 (Synthetic)',
   'Court 12 (Synthetic)',
   'Court 13 (Synthetic)']}]

In [91]:
!pip install fastapi uvicorn

Collecting fastapi
  Downloading fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Collecting uvicorn
  Downloading uvicorn-0.41.0-py3-none-any.whl.metadata (6.7 kB)
Collecting starlette>=0.46.0 (from fastapi)
  Downloading starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: pydantic>=2.7.0 in c:\users\crist\anaconda3\lib\site-packages (from fastapi) (2.12.5)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\crist\anaconda3\lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\crist\anaconda3\lib\site-packages (from fastapi) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: click>=7.0 in c:\users\crist\anaconda3\lib\site-packages (from uvicorn) (8.1.8)
Requirement already satisfied: h11>=0.8 in c:\users\crist\anaconda3\lib\site-packages (from uvicorn) (0.16.0)
Requirement already satisfied: colorama in c:\users\crist\anaconda3\lib\site-packages (from click>=7.0->uvicorn) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\crist\anaconda3\lib\site-packages (from pydantic>=2.7.0->fastapi) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\crist\anaconda3\lib\site-packages (from pydantic>=2.7.0->fastapi) (2.41.5)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\crist\anaconda3\lib\site-packages (from starlette>=0.46.0->fastapi) (4.7.0)
Requirement already satisfied: idna>=2.8 in c:\users\crist\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\crist\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (1.3.0)
Downloading fastapi-0.135.1-py3-none-any.whl (116 kB)
Downloading uvicorn-0.41.0-py3-none-any.whl (68 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading starlette-0.52.1-py3-none-any.whl (74 kB)
Installing collected packages: annotated-doc, uvicorn, starlette, fastapi

   ---------- ----------------------------- 1/4 [uvicorn]
   ---------- ----------------------------- 1/4 [uvicorn]
   ---------- ----------------------------- 1/4 [uvicorn]
   -------------------- ------------------- 2/4 [starlette]
   -------------------- ------------------- 2/4 [starlette]
   -------------------- ------------------- 2/4 [starlette]
   -------------------- ------------------- 2/4 [starlette]
   ------------------------------ --------- 3/4 [fastapi]
   ------------------------------ --------- 3/4 [fastapi]
   ------------------------------ --------- 3/4 [fastapi]
   ------------------------------ --------- 3/4 [fastapi]
   ---------------------------------------- 4/4 [fastapi]

Successfully installed annotated-doc-0.0.4 fastapi-0.135.1 starlette-0.52.1 uvicorn-0.41.0

In [ ]:
!uvicorn api:app --reload